// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpS7o2UmoT8AWE45Lr788ZuxaJ3EOUzw',
    appId: '1:270818752988:web:02a108cb1c9bdfc1f1f719',
    messagingSenderId: '270818752988',
    projectId: 'baitaplo',
    authDomain: 'baitaplo.firebaseapp.com',
    storageBucket: 'baitaplo.firebasestorage.app',
    measurementId: 'G-09440083LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCul8U_2-MuFnEef41FCKNumRirraDmbD4',
    appId: '1:270818752988:android:6095a4254a6a22c9f1f719',
    messagingSenderId: '270818752988',
    projectId: 'baitaplo',
    storageBucket: 'baitaplo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwR4S4GQNO5icSBUjQshODTH2emOTkMJg',
    appId: '1:270818752988:ios:24a93aa3343e59edf1f719',
    messagingSenderId: '270818752988',
    projectId: 'baitaplo',
    storageBucket: 'baitaplo.firebasestorage.app',
    iosBundleId: 'com.example.baitaplon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwR4S4GQNO5icSBUjQshODTH2emOTkMJg',
    appId: '1:270818752988:ios:24a93aa3343e59edf1f719',
    messagingSenderId: '270818752988',
    projectId: 'baitaplo',
    storageBucket: 'baitaplo.firebasestorage.app',
    iosBundleId: 'com.example.baitaplon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQpS7o2UmoT8AWE45Lr788ZuxaJ3EOUzw',
    appId: '1:270818752988:web:e71fcc5636fad97df1f719',
    messagingSenderId: '270818752988',
    projectId: 'baitaplo',
    authDomain: 'baitaplo.firebaseapp.com',
    storageBucket: 'baitaplo.firebasestorage.app',
    measurementId: 'G-NS8CX1DMN0',
  );

}