// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVh1h886tEBajr9h0JWOXhNZomrIUaHc',
    appId: '1:182240527615:web:d2124bd972e9ca411978ca',
    messagingSenderId: '182240527615',
    projectId: 'quanlysinhvien-4c9a9',
    authDomain: 'quanlysinhvien-4c9a9.firebaseapp.com',
    storageBucket: 'quanlysinhvien-4c9a9.firebasestorage.app',
    measurementId: 'G-9Z7XH2PHRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtk0zHEi15cpb8ob5B6P4vQckQEllqI0Y',
    appId: '1:182240527615:android:b3bc0ef424911f1a1978ca',
    messagingSenderId: '182240527615',
    projectId: 'quanlysinhvien-4c9a9',
    storageBucket: 'quanlysinhvien-4c9a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTfzqngoVXV1WiffUqbzQ6G_2AkiHWbU',
    appId: '1:182240527615:ios:21c27490de0c50a01978ca',
    messagingSenderId: '182240527615',
    projectId: 'quanlysinhvien-4c9a9',
    storageBucket: 'quanlysinhvien-4c9a9.firebasestorage.app',
    iosBundleId: 'com.example.baitaplon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTfzqngoVXV1WiffUqbzQ6G_2AkiHWbU',
    appId: '1:182240527615:ios:21c27490de0c50a01978ca',
    messagingSenderId: '182240527615',
    projectId: 'quanlysinhvien-4c9a9',
    storageBucket: 'quanlysinhvien-4c9a9.firebasestorage.app',
    iosBundleId: 'com.example.baitaplon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoVh1h886tEBajr9h0JWOXhNZomrIUaHc',
    appId: '1:182240527615:web:90e6f68d2df2cc371978ca',
    messagingSenderId: '182240527615',
    projectId: 'quanlysinhvien-4c9a9',
    authDomain: 'quanlysinhvien-4c9a9.firebaseapp.com',
    storageBucket: 'quanlysinhvien-4c9a9.firebasestorage.app',
    measurementId: 'G-R2PHZQGC0F',
  );
}
